= DustArch: DustVoice's Arch Linux from scratch
David Holland <info@dustvoice.de>
v2.6, 2019-10-24
:toc: left
:toc-title: Table Of Contents
:toclevels: 4
:doctype: book
:docinfo: shared
:source-highlighter: pygments
:last-update-label: Last modified:
:table-caption!:

== Inside the archiso

This section is aimed at providing help with the general installation of the customized archlinux from within official archlinux image.

=== Updating the system

First of we need to sync pacman up

[source, console]
----
root@archiso ~ # pacman -Sy
----

[NOTE]
====
After that, you will now be able to install packages with pacman.
====

=== Formatting the drive

First you have to list all the available drives by issuing

[source, console]
----
root@archiso ~ # fdisk -l
----

[NOTE]
====
The output of `fdisk -l` is dependent on your system configuration.
====

In my case, the partition I want to install the root filesystem on is `/dev/sdb2`. `/dev/sdb3` will be my swap partition.

[NOTE]
====
A swap size twice the size of your RAM is recommended by a lot of people. You should make the swap size *at least your RAM size* though.
====

[IMPORTANT]
====
If you haven't yet partitioned your disk, please refer to a general partitioning tutorial in the arch-wiki.
====

Now we need to format the partitions accordingly

[source, console]
----
root@archiso ~ # mkfs.ext4 /dev/sdb2
root@archiso ~ # mkswap /dev/sdb3
----

After doing that, we can enable the swap and mount the root partition.

[source, console]
----
root@archiso ~ # swapon /dev/sdb3
root@archiso ~ # mount /dev/sdb2 /mnt
----

[NOTE]
====
If you have an additional *EFI system partition*, because of a _UEFI - GPT_ setup or e.g. an existing Windows installation, which we will assume to be located under `/dev/sda2` (`/dev/sda` is the disk of my Windows install), you'll have to mount this partition to the new systems `/boot` folder

[source, console]
----
root@archiso ~ # mkdir /mnt/boot
root@archiso ~ # mount /dev/sda2 /mnt/boot
----
====

=== Preparing the chroot environment

First it might make sense to edit `/etc/pacman.d/mirrorlist` to move the mirror(s) geographically closest to you to the top.

After that we can either install the bare minimum packages needed

[source, console]
----
root@archiso ~ # pacstrap /mnt base linux linux-firmware
----

or install all packages present on the archiso, which makes sense in our case

[source, console]
----
root@archiso ~ # pacstrap /mnt base base-devel linux linux-firmware $(pacman -Qq | tr '\n' ' ')
----

This could take quite some time depending on your internet connection speed.

After that generate a `fstab` using `genfstab`

[source, console]
----
root@archiso ~ # genfstab -U /mnt >> /mnt/etc/fstab
----

and you're ready to go entering the chroot environment.

=== Entering the chroot

[source, console]
----
root@archiso ~ # arch-chroot /mnt
----

Et voila, you're inside the new os, greeted by a bash prompt.

==== Installing additional packages

First we'll make sure we get ourselves some basic utilities and enable the `dhcpcd` service, in order for the internet connection to work upon booting in our fresh system later.

[source, console]
----
[root@archiso /]# pacman -S sudo iputils dhcpcd grub dosfstools os-prober mtools
[root@archiso /]# systemctl enable dhcpcd
----

If you use `UEFI`, you'll also need

[source, console]
----
[root@archiso /]# pacman -S efibootmgr
----

Furthermore you'll probably need an editor. I'll use `neovim`

[source, console]
----
[root@archiso /]# pacman -S neovim
----

==== Changing the keyboard layout

The next thing you probably wanna do, at least if you're me, is to change the keyboard layout. In my case I'll adapt the standard `us` layout, so the `Caps_Lock` key will be mapped to `Escape`.

`Neovim` saves me from a ton of headaches, by providing the functionality to edit `gzip` files directly.

In my case I'll copy the `us` and `us-acentos` to `custom-us` and `custom-us-acentos` respectively

[source, console]
----
[root@archiso /]# cp /usr/share/kbd/keymaps/i386/qwerty/us.map.gz /usr/share/kbd/keymaps/i386/qwerty/custom-us.map.gz
[root@archiso /]# cp /usr/share/kbd/keymaps/i386/qwerty/us-acentos.map.gz /usr/share/kbd/keymaps/i386/qwerty/custom-us-acentos.map.gz
----

and change the line

./usr/share/kbd/keymaps/i386/qwerty/custom-us.map.gz
[source, text]
----
keycode 58 = Caps_Lock
----

to

./usr/share/kbd/keymaps/i386/qwerty/custom-us.map.gz
[source, text]
----
keycode 58 = Escape
----

in both created files.

Now you are able to load the keymap and set it as the default one to use respectively

[source, console]
----
root@archiso ~ # loadkeys custom-us
root@archiso ~ # localectl set-keymap custom-us
----

==== Master of time

After that you have to set your timezone and update the system clock. Generally speaking, you can find all the different timezones under `/usr/share/zoneinfo`. For me it is `/usr/share/zoneinfo/Europe/Berlin` and I had to issue

[source, console]
----
[root@archiso /]# ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime
[root@archiso /]# hwclock --systohc --utc
----

Now you can also enable time synchronization over network and check that everything is alright

[source, console]
----
[root@archiso /]# timedatectl set-timezone Europe/Berlin
[root@archiso /]# timedatectl set-ntp true
[root@archiso /]# timedatectl status
----

==== Master of locales

After that you have to generate your locale information. For that you have to edit `/etc/locale.gen` and uncomment the locale lines you want to enable.
I recommend to always uncomment `en_US.UTF-8 UTF8` for development purposes, even if you want to use another language primarily.
In my case I uncommented

./etc/locale.gen
[source, text]
----
[...]
#en_US.UTF-8 UTF8
[...]
----

which then became

./etc/locale.gen
[source, text]
----
[...]
en_US.UTF-8 UTF8
[...]
----

After that you still have to actually generate the locales by issuing

[source, console]
----
[root@archiso /]# locale-gen
----

and set the locale

[source, console]
----
[root@archiso /]# localectl set-locale LANG="en_US.UTF-8"
----

and we're done with this part.

==== Naming your machine

Now we can set the `hostname` and add `hosts` entries.

===== Hostname

To change the `hostname`, simply edit `/etc/hostname`, enter the desired name, then save and quit.

[source, console]
----
[root@archiso /]# vim /etc/hostname
----

which in my case then cointains

./etc/hostname
[source, text]
----
DustArch
----

===== Hosts

Now we need to specify some `hosts` entries by editing `/etc/hosts`

[source, console]
----
[root@archiso /]# vim /etc/hosts
----

And originall looked like this

./etc/hosts
[source, text]
----
# Static table lookup for hostnames.
# See hosts(5) for details.
----

and now looks like this

./etc/hosts
[source, text]
----
# Static table lookup for hostnames.
# See hosts(5) for details.

127.0.0.1   localhost           .
::1         localhost           .
127.0.1.1   DustArch.localhost  DustArch
----

==== User setup

Now you should probably change the default root password and create a new user for yourself, as using your new system purley through the native root user is not recommended from a security standpoint.

===== Give root a password

To change the password for the current user (the root user) do

[source, console]
----
[root@archiso /]# passwd
----

and choose a new password.

[#creating-my-personal-user]
===== Creating my personal user

We are going to make sure the `fish` shell is installed, create a new user, set the password for this user, make sure the `sudo` package is installed and allow the `wheel` group sudo access.

[source, console]
----
[root@archiso /]# pacman -S fish
[root@archiso /]# useradd -m -p "" -G "adm,audio,floppy,kvm,log,network,rfkill,scanner,storage,users,optical,power,wheel" -s /usr/bin/fish dustvoice
[root@archiso /]# passwd dustvoice
[root@archiso /]# pacman -S sudo
----

We now have to allow the `wheel` group sudo access. For that we edit

[source, console]
----
[root@archiso /]# sudo nvim /etc/sudoers
----

and uncomment the following line

./etc/sudoers
[source, text]
----
## Uncomment to allow members of group wheel to execute any command
# %wheel ALL=(ALL) ALL
----

so that it becomes the following

./etc/sudoers
[source, text]
----
## Uncomment to allow members of group wheel to execute any command
%wheel ALL=(ALL) ALL
----

You could also add a new line below

./etc/sudoers
[source, text]
----
root ALL=(ALL) ALL
----

with your new username

./etc/sudoers
[source, text]
----
dustvoice ALL=(ALL) ALL
----

to solely grant yourself sudo privileges.

=== Preparing to boot

Now onto installing the boot manager. We will use `grub` in this guide.

First make sure, all the required packages are installed

[source, console]
----
[root@archiso /]# pacman -S grub dosfstools os-prober mtools
----

and if you want to use `UEFI`, also

[source, console]
----
[root@archiso /]# pacman -S efibootmgr
----

==== BIOS

If you chose the `BIOS - MBR` variation, have to do nothing special

If you chose the `BIOS - GPT` variation, you'll have to have a `+1M` boot partition created with the partition type set to `BIOS boot` for `fdisk`.

In both cases you now have to run the following command

[source, console]
----
[root@archiso /]# grub-install --target=i386-pc /dev/sdb
----

[NOTE]
====
It is obvious, you have to replace `/dev/sda` with the disk you want to use. Note however that you have to specify a *disk* and *not a partition*, so *no number*.
====

==== UEFI

If you chose the `UEFI - GPT` variation, you'll have to have the `EFI System Partition` mounted (where `/dev/sda2` is the partition holding said `EFI System Partition` in my particular setup) and execute the following command

[source, console]
----
[root@archiso /]# grub_install --target=x86_64-efi --efi-directory=/boot --bootloader-id=grub --recheck
----

[IMPORTANT]
====
If you've planned on dual booting arch with Windows and therefore reused the `EFI System Partition` created by Windows, you might not be able to boot to grub just yet. In this case, boot into Windows, open a `cmd` window as administrator and type in

[source, console]
----
bcdedit /set {bootmgr} path \EFI\grub\grubx64.efi
----

To make sure that the path is correct, you can just

[source, console]
----
[root@archiso /]# ls /boot/EFI/grub
----

to make sure, that the `grubx64.efi` file is really there.

Now you should be good to go.
====

==== Grub config

In all cases, you now have to create the main configuration file

[source, console]
----
[root@archiso /]# grub-mkconfig -o /boot/grub/grub.cfg
----

Now you're good to boot into your new system

== Inside the DustArch

=== Someone there?

First we have to check if the internet connection is set up properly

[source, console]
----
dustvoice@DustArch ~> ip link
----

This outputs the interface status report. To make sure that you really have a working _internet_ connection, issue

[source, console]
----
dustvoice@DustArch ~> ping archlinux.org
----

Everything should run smoothly. If not, try running

[source, console]
----
dustvoice@DustArch ~> sudo systemctl restart dhcpcd
----

and then try `ping` again.

=== Update and upgrade

After making sure that you have established an internet connection, you can then proceed to update and upgrade all installed packages by issuing

[source, console]
----
dustvoice@DustArch ~> sudo pacman -Syu
----

=== Setting the correct shell

I'll be using the `fish` shell.

We already set the correct shell for the `dustvoice` user in the <<creating-my-personal-user>> step, but I want to use `fish` for the `root` user too, so I'll have to change ``root``'s default shell to it.

[source, console]
----
dustvoice@DustArch ~> chsh -s /usr/bin/fish root
----

Don't worry about the looks by the way, we're gonna change all that in just a second.

=== Version control

Next you'll probably want to install `git`. Just do

[source, console]
----
dustvoice@DustArch ~> sudo pacman -S git
----

and you're good to go. We'll care about the `.gitconfig` in just a second.

=== Security is important

If you've followed the tutorial using a recent version of arch linux, you'll probably already have the most recent version of `gnupg` installed by default. Just to make sure, issue

[source, console]
----
dustvoice@DustArch ~> sudo pacman -S gnupg
----

==== Smartcard shenanigans

After that you'll still have to setup `gnupg` correctly. In my case I have my private keys stored on a smartcard. To use it, I'll have to install some packages first

[source, console]
----
dustvoice@DustArch ~> sudo pacman -S pcsclite libusb-compat ccid opensc
----

and then enable and start the `pcscd` service

[source, console]
----
dustvoice@DustArch ~> sudo systemctl enable pcscd
dustvoice@DustArch ~> sudo systemctl start pcscd
----

Note however that your mileage may vary.

[#additional-tools-setup-home]
=== Additional required tools

[source, console]
----
dustvoice@DustArch ~> pacman -S make cmake clang jdk-openjdk pyhton pyhton-pip pass openssh
----

[#setup-home]
=== Setting up a home environment

In this step we're going to setup a home environment for both the `root` and my personal `dustvoice` user. 

[NOTE]
====
In my case these 2 home environments are mostly equivalent, which is why I'll execute the follwing commands as the `dustvoice` user first and then `su` into the `root` user and repeat the same commands.
====

[NOTE]
====
In my case, I want to access all my git repositories with my `gpg` key on my smartcard. For that I have to configure the `gpg-agent` though. So I will have to reside to first use the `https` url and later change the url in the corresponding `.git/config` file.
====

[source, console]
----
dustvoice@DustArch ~> git init
dustvoice@DustArch ~> git remote add origin https://github.com/DustVoice/dotfiles.git
dustvoice@DustArch ~> git fetch
dustvoice@DustArch ~> git reset origin/master --hard
dustvoice@DustArch ~> git branch --set-upstream-to=origin/master master
----

Before we'll be able to update the ``submodule``s (`nvim` config files and ``pass``word-store), we will have to setup our `gpg` key as a `ssh` key

[source, console]
----
[I] dustvoice@DustArch ~>
$ chmod 700 .gnupg
[I] dustvoice@DustArch ~>
$ gpg --card-status
[I] dustvoice@DustArch ~>
$ gpg --card-edit
(insert) gpg/card> fetch
(insert) gpg/card> q
[I] dustvoice@DustArch ~>
$ gpg-connect-agent updatestartuptty /bye
[I] dustvoice@DustArch ~>
$ git remote set-url origin git@github.com:DustVoice/dotfiles.git
[I] dustvoice@DustArch ~>
$ exit
----

[NOTE]
====
You would have to adapt the keygrip present in the sshcontrol file to your keygrip, retrieved with `gpg -K --with-keygrip`.
====

Now log back in and continue

[source, console]
----
[I] dustvoice@DustArch ~
$ git submodule update --init --recursive
[I] dustvoice@DustArch ~
$ cd .config/nvim
[I] dustvoice@DustArch ~/.config/nvim
$ echo 'let g:platform = "linux"' >> platform.vim
[I] dustvoice@DustArch ~/.config/nvim
$ echo 'let g:use_autocomplete = 3' >> custom.vim
[I] dustvoice@DustArch ~/.config/nvim
$ echo 'let g:use_clang_format = 1' >> custom.vim
[I] dustvoice@DustArch ~/.config/nvim
$ echo 'let g:use_font = 0' >> custom.vim
[I] dustvoice@DustArch ~/.config/nvim
$ pip3 install neovim
[I] dustvoice@DustArch ~/.config/nvim
$ nvim --headless +PlugInstall +qa
[I] dustvoice@DustArch ~/.config/nvim
$ cd plugged/YouCompleteMe
[I] dustvoice@DustArch ~/.config/nvim/plugged/YouCompleteMe
$ python3 install.py --clang-completer --java-completer
[I] dustvoice@DustArch ~/.config/nvim/plugged/YouCompleteMe
$ cd ~
----

Your personal environment will be complete, after getting `JUCE` and `FRUT`

[source, console]
----
[I] dustvoice@DustArch ~
$ git clone https://github.com/WeAreROLI/JUCE.git
[I] dustvoice@DustArch ~
$ cd JUCE
[I] dustvoice@DustArch ~/JUCE
$ git checkout develop
[I] dustvoice@DustArch ~/JUCE
$ cd ..
[I] dustvoice@DustArch ~
$ git clone https://github.com/McMartin/FRUT.git
----

[NOTE]
====
As mentioned before, you would now switch to the `root` user, either by logging in as root, or ``su``ing, and go back to <<setup-home>> to repeat all commands for the root user.
====

=== Password management

I'm using `pass` as my password manager. We already installed it in the <<additional-tools-setup-home>> step.

=== Python

Python has become really important for a magnitude of use cases. We need `python3` in particular as well as the `pip` for it.
For `asciidoctor` _(will be installed in just a second)_ we also need to install the `pygments` package.

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S python python-pip
[I] dustvoice@DustArch ~
$ sudo pip3 install pygments
----

=== Ruby & Asciidoctor

In order to use `asciidoctor`, we have to install `ruby` and `rubygems`. After that we can install `asciidoctor` and all it's required gems.

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S ruby rubygems
[I] dustvoice@DustArch ~
$ gem install asciidoctor --pre
[I] dustvoice@DustArch ~
$ gem install asciidoctor-pdf --pre
[I] dustvoice@DustArch ~
$ gem install asciidoctor-epub3 --pre
[I] dustvoice@DustArch ~
$ gem install pygments.rb --pre
----

Now the only thing left (in my case) is adding `~/.gem/ruby/2.6.0/bin` to your path. For `fish` you'll want to run the following command

[source, console]
----
[I] dustvoice@DustArch ~
$ set -U fish_user_paths $fish_user_paths ~/.gem/ruby/2.6.0/bin
----

[NOTE]
====
If you use another shell than `fish`, you might have to do something different to add a directory to your `PATH`.

Also please note that if you run a ruby version different from `2.6.0`, you have to use the `bin` path for that version.
====

==== Additional Development tools

Here are just some examples of development tools one could install in addition to what we already have.

===== Code formatting

We already have `clang-format` as a code formatter, but this only works for `C` languages. For the `java` part, we can use `astyle`.

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S astyle
----

===== Documentation

To generate a documentation from source code, I mostly use `doxygen`

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S doxygen
----

===== Build tools

In addition to `make`, I'll often times use `ninja` for my builds

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S ninja
----

=== Audio

Well, why wouldn't you want audio...

==== ALSA

To quickly setup audio, install `alsa` and `alsa-utils`

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S alsa alsa-utils
----

Now choose the soundcard you want to use

[source, console]
----
[I] dustvoice@DustArch ~
$ cat /proc/asound/cards
----

and then create `/etc/asound.conf`

./etc/asound.conf
[source, text]
----
defaults.pcm.card 2
defaults.ctl.card 2
----

[NOTE]
====
It should be apparent, that you would have to switch out `2` witht the number corresponding to the soundcard you want to use.
====

==== Pulse Audio

Some applications require `pulseaudio` or work better with it (for example `discord`), so it might make sense to use `pulseaudio`

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S pulseaudio pulsemixer
----

For enabling realtime priority for `pulseaudio` on arch, please make sure your user is part of the `audio` group and edit the file `/etc/pulse/daemon.conf` so that you uncomment the lines

[source, text]
----
; high-priority = yes
; nice-level = -11

; realtime-scheduling = yes
; realtime-priority = 5
----

to

[source, text]
----
high-priority = yes
nice-level = -11

realtime-scheduling = yes
realtime-priority = 5
----

If your system can handle the load, you can also increase the remixing quality, by changing

[source, text]
----
; resample-method = speex-float-1
----

to

[source, text]
----
resample-method = speex-float-10
----

Of course a restart of the `pulseaudio` daemon is mandatory.

[source, console]
----
[I] dustvoice@DustArch ~
$ pulseaudio --kill
[I] dustvoice@DustArch ~
$ pulseaudio --start
----

=== Graphical desktop environment

If you decide, that you want to use a graphical desktop environment, you have to install additional packages in order for that to work.

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S xorg xorg-xinit xorg-drivers i3 i3status rofi ttf-hack xfce4-terminal alsa alsa-utils wicd arandr
----

==== NVIDIA

If you also want to use NVIDIA functionality, for example for `davinci-resolve`, you would need to install their proprietary driver

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S nvidia nvidia-utils nvidia-settings opencl-nvidia
----

[NOTE]
====
You would have to reboot sooner or later after installing the NVIDIA drivers.

Also to get the best performance, at least for something like screen capturing in `obs`, go to *X Server Display Configuration* inside `nvidia-settings`, switch to *Advanced* and enable *Force Composition Pipeline*, as well as *Force Full Composition Pipeline*.
====

==== Launching the grahpical environment

After that you can now do `startx` in order to launch the graphical environment.

If anything goes wrong in the process, remember that you can press *Ctrl+Alt+<Number>* to switch ``tty``s.

=== GUI Software

As you now have a working graphical desktop environment, you might want to install some software to utilize your newly gained power

==== Desktop background

You might want to consider installing `nitrogen`, in order to be able to set a background image

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S nitrogen
----

==== Compositing software

To get buttery smooth animation as well as e.g. video playback in `brave`, you might want to consider using a `compton` based software named `picom`

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S picom
----

Now edit the file `~/.config/i3/config` and uncomment the `picom` line in order to start `picom` with `i3`.

[WARNING]
====
In order for ``obs``' screen capture to work correctly, you need to kill `picom` completely before using `obs`.

[source, console]
----
[I] dustvoice@DustArch ~
$ pkill picom
----

or

[source, console]
----
[I] dustvoice@DustArch ~
$ ps aux | grep picom
[I] dustvoice@DustArch ~
$ kill <pid>
----
====

==== X clipboard

To copy something from the terminal to the x clipboard, use `xclip`

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S xclip
[I] dustvoice@DustArch ~
$ xclip some_random_text
----

==== Taking screenshots

For this functionality, especially in combination with `rofi`, use `scrot`

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S scrot
[I] dustvoice@DustArch ~
$ scrot filename.png
----

==== Image viewer

Now that we can create screenshots, we might also want to view those

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S ristretto
[I] dustvoice@DustArch ~
$ ristretto filename.png
----

==== File manager

You probably also want to use a file manager. In my case, `thunar`, the `xfce` file manager, worked best.

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S thunar
----

To also be able to mount removable drives, without root, and in order to have a GUI for mounting stuff, you would need to install `gigolo` and `gvfs`

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S gigolo gvfs
----

==== Archive manager

As we now have a file manager, it might be annoying, to open up a terminal everytime you simply want to extract an archive of some sort.

That's why we'll install `xarchiver`.

In order for `xarchiver` to work its full potential we're first gonna install some additional archive types

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S p7zip zip unrar cpio
----

Now we can proceed to install `xarchiver`

[source, console]
----
[I] dustvoice@DustArch ~
$ xarchiver
----

==== Partition management

You may also choose to use a graphical partitioning software instead of `fdisk` or `cfdisk`. For that you can install `gparted`

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S gparted
----

==== PDF viewer

As we've installed `asciidoctor-pdf` previously, you might be wondering how you are supposed to open the generated pdfs. There are two ways.

===== Using the GUI

Installing `mupdf` is as simple as issuing

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S mupdf
----

If you want to have changes made to the pdf reflected immediately in the viewer, you would need `evince` instead

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S evince
----

===== Using the framebuffer

If you want to not always use the graphical desktop with `mupdf`, you might be interested in the `fbgs` software.

This software renders a pdf document using the native framebuffer. To install it simply do

[source, console]
----
[I] dustvoice@DustArch ~
$ pacman -S fbida ghostscript
----

and to view this pdf document (`Documentation.pdf`) for example, you would run

[source, console]
----
[I] dustvoice@DustArch ~
$ fbgs Documentation.pdf
----

[INFO]
====
You can view all the controls by pressing `h`.
====

==== Web browser

As you're already using a GUI, you also might be interested in a web browser. In my case, I'll install `brave` from the AUR as well as `browserpass` from the official repositories for using my passwords in `brave`.

[source, console]
----
[I] dustvoice@DustArch ~
$ git clone https://aur.archlinux.org/brave-bin.git
[I] dustvoice@DustArch ~/brave-bin
$ makepkg -si
[I] dustvoice@DustArch ~/brave-bin
$ cd ..
[I] dustvoice@DustArch ~
$ rm -rf brave-bin
[I] dustvoice@DustArch ~
$ sudo pacman -S browserpass
----

Now we still have to setup `browserpass`

[source, console]
----
[I] dustvoice@DustArch ~
$ cd /usr/local/lib/browserpass
[I] dustvoice@DustArch /usr/local/lib/browserpass
$ make hosts-brave-user
[I] dustvoice@DustArch /usr/local/lib/browserpass
$ make policies-brave-user
[I] dustvoice@DustArch /usr/local/lib/browserpass
$ cd ~
----

Now the only thing left is, to fire up `brave` and install the `browserpass` extension from the chrome store.

===== Entering the dark side

You might have to be completely anonymous whilst browsing the web at some point. Although this shouldn't be your only precaution, using `tor-browser` would be the first thing to use

[source, console]
----
[I] dustvoice@DustArch ~
$ git clone https://aur.archlinux.org/tor-browser.git
[I] dustvoice@DustArch ~
$ cd tor-browser
[I] dustvoice@DustArch ~/tor-browser
$ makepkg -si
[I] dustvoice@DustArch ~/tor-browser
$ cd ..
[I] dustvoice@DustArch ~
$ rm -rf tor-browser
----

==== Office utilities

For now we'll install `libreoffice-fresh`

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S libreoffice-fresh
----

==== Printing

In order for printing to work with my printer, which is a _Brother MFC J497DW_, I had do install `avahi`, `cups`, `cups-pdf`, `nss-mdns` and the correspoding driver for my printer. In order to be able to print from the `gtk` print dialogue, we'll also need to install `system-config-printer` and `print-manager`.

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S avahi
[I] dustvoice@DustArch ~
$ sudo pacman -S cups cups-pdf nss-mdns
[I] dustvoice@DustArch ~
$ git clone https://aur.archlinux.org/brother-mfc-j497dw.git
[I] dustvoice@DustArch ~
$ cd brother-mfc-j497dw
[I] dustvoice@DustArch ~/brother-mfc-j497dw
$ makepkg -si
[I] dustvoice@DustArch ~/brother-mfc-j497dw
$ cd ..
[I] dustvoice@DustArch ~
$ rm -rf brother-mfc-j497dw
[I] dustvoice@DustArch ~
$ sudo systemctl enable avahi-daemon.service
[I] dustvoice@DustArch ~
$ sudo systemctl start avahi-daemon.service
----

Now you have to edit `/etc/nsswitch.conf`

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo nvim /etc/nsswitch.conf
----

so this line

[source, text]
----
hosts: files mymachines myhostname resolve [!UNAVAIL=return] dns
----

becomes this line

[source, text]
----
hosts: files mymachines myhostname mdns4_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns
----

Now continue with this

[source, text]
----
[I] dustvoice@DustArch ~
$ avahi-browse --all --ignore-local --resolve --terminate
[I] dustvoice@DustArch ~
$ sudo systemctl enable org.cups.cupsd.service
[I] dustvoice@DustArch ~
$ sudo systemctl start org.cups.cupsd.service
[I] dustvoice@DustArch ~
$ sudo pacman -S system-config-printer print-manager
----

Now just open up `system-config-printer` and configure your printer.

To test if everything is working, you could open up `brave`, the go to *Print* and then try printing.

==== Process management

The native linux tool to have a CLI task-manager, is `top`.

The next evolutionary step would be `htop`, which is a improved version of `top` (like `vi` and `vim` for example)

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S htop
----

If you prefer a GUI for that kind of task, install `xfce4-taskmanager`

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S xfce4-taskmanager
----

==== Communication

Life is all about communicating. Here are some pieces of software to do exactly that.

===== Email

There is nothing better than some classical email.

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S thunderbird
----

===== Telegram

You want to have your `telegram` messages on your desktop pc?

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S telegram-desktop
----

===== TeamSpeak 3

Wanna chat with your gaming friends and they have a `teamspeak3` server? Go for it

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S teamspeak3
----

===== Discord

You'd rather use `discord`? No problem

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S discord
----

==== Video software

Just some additional software related to videos.

===== Viewing video

You might consider using `vlc`

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S vlc
----

===== Creating video

`obs` should be the right choice

[source, console]
----
[I] dustvoice@DustArch ~
$ git clone https://aur.archlinux.org/obs-studio-git
[I] dustvoice@DustArch ~
$ cd obs-studio-git
[I] dustvoice@DustArch ~/obs-studio-git
$ makepkg -si
[I] dustvoice@DustArch ~/obs-studio-git
$ cd ..
[I] dustvoice@DustArch ~
$ rm -rf obs-studio-git
----

===== Live stream a terminal session

For this task, you'll need a program called `tmate`. Just install it

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S tmate
----

and run it

[source, console]
----
[I] dustvoice@DustArch ~
$ tmate
----

===== Editing video

In my case, I'm using `davinci-resolve`.

But before installing `davinci-resolve`, we have to enable 32-bit packages.
Just edit `/etc/pacman.conf` and uncomment the `multilib` lines.

Then update your packages

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -Sy
----

and install `davinci-resolve`

[source, console]
----
[I] dustvoice@DustArch ~
$ git clone https://aur.archlinux.org/davinci-resolve.git
[I] dustvoice@DustArch ~
$ cd davinci-resolve
[I] dustvoice@DustArch ~/davinci-resolve
$ makepkg -si
[I] dustvoice@DustArch ~/davinci-resolve
$ cd ..
[I] dustvoice@DustArch ~
$ rm -rf davinci-resolve
----

===== Utilizing video

Wanna remote control your/another pc? `teamviewer` might just be the right choice for you

[source, console]
----
[I] dustvoice@DustArch ~
$ git clone https://aur.archlinux.org/teamviewer.git
[I] dustvoice@DustArch ~
$ cd teamviewer
[I] dustvoice@DustArch ~/teamviewer
$ makepkg -si
[I] dustvoice@DustArch ~/teamviewer
$ cd ..
[I] dustvoice@DustArch ~
$ rm -rf teamviewer
----

==== Ardour

To e.g. edit and produce audio, I would recommend `ardour`, because it's easy to use, stable and cross platform.

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S ardour
----

[NOTE]
====
You might have to edit `/etc/security/limits.conf`, to increase the allowed locked memory amount.

In my case I have 32GB of RAM and I want the `audio` group to be allocate most of the RAM, which is why I added the following line to the file

[source, text]
----
@audio - memlock 29360128
----
====

[INFO]
====
Ardour won't natively save in the `mp3` format due to licensing stuff. In order to create `mp3` files, for sharing with other devices that have problems with `wav` files for example, you can just use `ffmpeg`.

First make sure it's installed

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S ffmpeg
----

and after that we're going to convert `in.wav` to `out.mp3`

[source, console]
----
[I] dustvoice@DustArch ~
$ ffmpeg -i in.wav -acodec mp3 out.mp3
----
====

==== Switching GPUs (NVIDIA)

To switch from the NVIDIA GPU to the Intel integraded one, one could use `optimus-manager`

[source, console]
----
[I] dustvoice@DustArch ~
$ git clone https://aur.archlinux.org/optimus-manager.git
[I] dustvoice@DustArch ~
$ cd optimus-manager
[I] dustvoice@DustArch ~/optimus-manager
$ makepkg -si
[I] dustvoice@DustArch ~/optimus-manager
$ cd ..
[I] dustvoice@DustArch ~
$ rm optimus-manager
[I] dustvoice@DustArch ~
$ sudo systemctl enable optimus-manager.service
[I] dustvoice@DustArch ~
$ sudo systemctl start optimus-manager.service
----

[NOTE]
====
As the installation script correctly informs you, a full reboot is required before using `optimus-manager`.
====

Now you can simply switch to the Intel GPU, by using

[source, console]
----
[I] dustvoice@DustArch ~
$ optimus-manager --switch intel
----

and switch back to NVIDIA by using

[source, console]
----
[I] dustvoice@DustArch ~
$ optimus-manager --switch nvidia
----

[WARNING]
====
This will close all graphical sessions and tehrefore close all current applications.
====

Furthermore, you can set the default GPU to use.

If you want Intel GPU at startup use

[source, console]
----
[I] dustvoice@DustArch ~
$ optimus-manager --set-startup intel
----

or if you want the NVIDIA GPU, use

[source, console]
----
[I] dustvoice@DustArch ~
$ optimus-manager --set-startup nvidia
----

[NOTE]
====
For enabling power management, read link:https://github.com/Askannz/optimus-manager/wiki[] in the section _A guide to power management options_.
====

==== Virtualization

You might need to run another os, for example Mac OS, from within Linux, e.g. for development/testing purposes. For that you can use `virtualbox`

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S virtualbox
----

// TODO: After getting a system with 2 GPUs, add part for KVMing a Windows.
// Resources:
// - virt-manager
// - wiki.archlinux.org/index.php/KVM
// - wiki.debian.org/VGAPassthrough
// - ycnrg.org/vga-passthrough-with-ovmf-vfio
// - bufferoverflow.io/gpu-passthrough
// - heiko-sieger.info/running-windows-10-on-linux-using-kvm-with-vga-passthrough
// - openwebit.com/c/how-to-run-windows-vm-on-more-than-2-cores-under-kvm

==== Gaming

The first option for native/emulated gaming on linux is obviously `steam`.

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S steam lib32-nvidia-utils pulseaudio pulseaudio-alsa lib32-libpulse
----

The second option would be `lutris`, a program, that configures a wine instance correctly, etc.

[source, console]
----
[I] dustvoice@DustArch ~
$ sudo pacman -S lutris
----

== DustArch package list

A complete list of all the packages present on the DustArch.

.packages-x86_64
[source, text, linenums]
----
a52dec
acl
adobe-source-code-pro-fonts
adwaita-icon-theme
alsa-lib
alsa-plugins
alsa-topology-conf
alsa-ucm-conf
alsa-utils
amd-ucode
aom
apr
apr-util
arandr
arch-install-scripts
archlinux-keyring
ardour
argon2
aribb24
aspell
astyle
at-spi2-atk
at-spi2-core
atk
atkmm
attica
attr
aubio
audit
autoconf
autoconf-archive
automake
avahi
b43-fwcutter
base
bash
bc
bind-tools
binutils
bison
bluez-libs
boost-libs
brave-bin
broadcom-wl
brother-mfc-j497dw
brotli
browserpass
btrfs-progs
bubblewrap
bzip2
bzr
c-ares
ca-certificates
ca-certificates-mozilla
ca-certificates-utils
cairo
cairomm
cantarell-fonts
ccid
cdparanoia
celt0.5.1
clang
clonezilla
clucene
cmake
colord
compiler-rt
confuse
coreutils
cpio
cracklib
crda
cryptsetup
cups
cups-filters
cups-pdf
curl
darkhttpd
dav1d
davinci-resolve
db
dbus
dbus-glib
dconf
ddrescue
desktop-file-utils
device-mapper
devtools
dhclient
dhcpcd
dialog
diffutils
ding-libs
discord
djvulibre
dkms
dmraid
dnsmasq
dnssec-anchors
docbook-xml
docbook-xsl
dosfstools
double-conversion
doxygen
drbl
e2fsprogs
ecryptfs-utils
efibootmgr
efitools
efivar
egl-wayland
eglexternalplatform
elinks
enchant
ethtool
evince
exfat-utils
exo
expat
f2fs-tools
faad2
fakeroot
fbida
ffmpeg
fftw
file
filesystem
findutils
fish
flac
flex
fontconfig
freeglut
freetype2
fribidi
fsarchiver
fuse-common
fuse2
fuse3
gawk
gc
gcc
gcc-libs
gconf
gcr
gdbm
gdk-pixbuf2
geoip
geoip-database
gettext
ghostscript
giblib
giflib
gigolo
git
glew
glib-networking
glib2
glib2-docs
glibc
glibmm
glu
gmp
gnome-common
gnome-desktop
gnu-free-fonts
gnu-netcat
gnupg
gnutls
gobject-introspection-runtime
gparted
gperf
gpgme
gpm
gptfdisk
graphene
graphite
grep
grml-zsh-config
groff
grub
gsettings-desktop-schemas
gsfonts
gsm
gspell
gssproxy
gst-plugins-base
gst-plugins-base-libs
gstreamer
gtk-doc
gtk-update-icon-cache
gtk2
gtk3
gtkmm
gtkmm3
guile
gvfs
gzip
harfbuzz
harfbuzz-icu
haveged
hdparm
hicolor-icon-theme
hspell
htop
hunspell
hwids
hyphen
i3-gaps
i3blocks
i3lock
i3status
iana-etc
icu
ijs
imagemagick
imlib2
inetutils
intel-ucode
intltool
iproute2
iptables
iputils
ipw2100-fw
ipw2200-fw
irssi
iso-codes
itstool
iw
iwd
jack
jansson
jasper
java-environment-common
java-runtime-common
jbig2dec
jdk-openjdk
jfsutils
jq
jre-openjdk
jre-openjdk-headless
js60
json-c
json-glib
jsoncpp
karchive
kauth
kbd
kbookmarks
kcmutils
kcodecs
kcompletion
kconfig
kconfigwidgets
kcoreaddons
kcrash
kdbusaddons
kdeclarative
keyutils
kglobalaccel
kguiaddons
ki18n
kiconthemes
kio
kitemviews
kjobwidgets
kmod
knotifications
kpackage
krb5
kservice
ktextwidgets
kwallet
kwidgetsaddons
kwindowsystem
kxmlgui
l-smash
lame
lbzip2
lcms2
ldns
less
lftp
lib32-acl
lib32-alsa-lib
lib32-alsa-plugins
lib32-atk
lib32-attr
lib32-bzip2
lib32-cairo
lib32-dbus
lib32-e2fsprogs
lib32-expat
lib32-flac
lib32-fontconfig
lib32-freetype2
lib32-fribidi
lib32-gcc-libs
lib32-gdk-pixbuf2
lib32-gettext
lib32-glib2
lib32-glibc
lib32-glu
lib32-gmp
lib32-gnutls
lib32-gtk2
lib32-harfbuzz
lib32-icu
lib32-keyutils
lib32-krb5
lib32-lcms2
lib32-libappindicator-gtk2
lib32-libasyncns
lib32-libcap
lib32-libcups
lib32-libdatrie
lib32-libdbusmenu-glib
lib32-libdbusmenu-gtk2
lib32-libdrm
lib32-libelf
lib32-libffi
lib32-libgcrypt
lib32-libglvnd
lib32-libgpg-error
lib32-libice
lib32-libidn
lib32-libindicator-gtk2
lib32-libjpeg-turbo
lib32-libldap
lib32-libnl
lib32-libogg
lib32-libpcap
lib32-libpciaccess
lib32-libpng
lib32-libpng12
lib32-libpulse
lib32-libsm
lib32-libsndfile
lib32-libtasn1
lib32-libthai
lib32-libtiff
lib32-libusb
lib32-libvorbis
lib32-libx11
lib32-libxau
lib32-libxcb
lib32-libxcomposite
lib32-libxcursor
lib32-libxdamage
lib32-libxdmcp
lib32-libxext
lib32-libxfixes
lib32-libxft
lib32-libxi
lib32-libxinerama
lib32-libxml2
lib32-libxrandr
lib32-libxrender
lib32-libxshmfence
lib32-libxss
lib32-libxtst
lib32-libxxf86vm
lib32-llvm-libs
lib32-lm_sensors
lib32-lz4
lib32-mesa
lib32-ncurses
lib32-nettle
lib32-nspr
lib32-nss
lib32-nvidia-utils
lib32-openssl
lib32-p11-kit
lib32-pango
lib32-pcre
lib32-pixman
lib32-readline
lib32-sqlite
lib32-systemd
lib32-util-linux
lib32-wayland
lib32-xz
lib32-zlib
lib32-zstd
libabw
libaio
libarchive
libass
libassuan
libasyncns
libatasmart
libatomic_ops
libavc1394
libblockdev
libbluray
libbytesize
libcanberra
libcap
libcap-ng
libcddb
libcdio
libcdio-paranoia
libcdr
libcmis
libconfig
libcroco
libcups
libdaemon
libdatrie
libdbusmenu-glib
libdbusmenu-gtk2
libdbusmenu-qt5
libdca
libdmx
libdrm
libdvbpsi
libe-book
libebml
libedit
libelf
libepoxy
libepubgen
libetonyek
libev
libevdev
libevent
libexif
libexttextcat
libfdk-aac
libffi
libfontenc
libfreehand
libgcrypt
libglvnd
libgnome-keyring
libgpg-error
libgudev
libgusb
libgxps
libibus
libice
libid3tag
libidn
libidn2
libiec61883
libimobiledevice
libindicator-gtk2
libinput
libixion
libjpeg-turbo
libksba
liblangtag
libldap
liblo
liblouis
liblqr
liblrdf
libluv
libmad
libmatroska
libmm-glib
libmng
libmnl
libmodplug
libmpc
libmpcdec
libmpeg2
libmspub
libmwaw
libndp
libnet
libnetfilter_conntrack
libnewt
libnfnetlink
libnftnl
libnghttp2
libnl
libnm
libnotify
libnsl
libnumbertext
libodfgen
libogg
libomxil-bellagio
liborcus
libotr
libpagemaker
libpaper
libpcap
libpciaccess
libpgm
libpipeline
libplist
libpng
libpng12
libproxy
libpsl
libpulse
libqxp
libraqm
libraw1394
libreoffice-fresh
librevenge
librsvg
libsamplerate
libsasl
libseccomp
libsecret
libsigc++
libsm
libsndfile
libsodium
libsoup
libsoxr
libspectre
libssh
libssh2
libstaroffice
libsynctex
libtar
libtasn1
libteam
libtermkey
libthai
libtheora
libtiff
libtirpc
libtommath
libtool
libuiohook
libunistring
libunwind
libupnp
libusb
libusb-compat
libusbmuxd
libutempter
libutf8proc
libutil-linux
libuv
libva
libvdpau
libvisio
libvisual
libvoikko
libvorbis
libvpx
libvterm
libwacom
libwebp
libwnck3
libwpd
libwpe
libwpg
libwps
libx11
libxau
libxaw
libxcb
libxcomposite
libxcursor
libxdamage
libxdg-basedir
libxdmcp
libxext
libxfce4ui
libxfce4util
libxfixes
libxfont2
libxft
libxi
libxinerama
libxkbcommon
libxkbcommon-x11
libxkbfile
libxml2
libxmu
libxnvctrl
libxp
libxpm
libxrandr
libxrender
libxres
libxshmfence
libxslt
libxss
libxt
libxtst
libxv
libxvmc
libxxf86dga
libxxf86vm
libyaml
libzmf
licenses
lilv
linux
linux-api-headers
linux-atm
linux-firmware
llvm-libs
lm_sensors
lmdb
lpsolve
lrzip
lsb-release
lsscsi
lua
lua51
luajit
lvm2
lz4
lzo
lzop
m4
mailcap
make
mallard-ducktype
man-db
man-pages
mc
mdadm
media-player-info
memtest86+
mercurial
mesa
mesa-demos
meson
minizip
mkinitcpio
mkinitcpio-busybox
mkinitcpio-nfs-utils
mozilla-common
mpfr
msgpack-c
mtdev
mtools
mupdf
nano
nbd
ncurses
ndctl
ndisc6
neon
neovim
net-tools
netctl
nettle
networkmanager
nfs-utils
nfsidmap
nilfs-utils
ninja
nitrogen
nmap
node-gyp
nodejs
npm
npth
nspr
nss
nss-mdns
ntfs-3g
ntp
nvidia
nvidia-settings
nvidia-utils
obs-input-overlay-bin
obs-linuxbrowser-bin
obs-studio-git
ocl-icd
oniguruma
openal
opencl-nvidia
openconnect
opencore-amr
openjpeg2
openmotif
openresolv
opensc
openssh
openssl
openssl-1.0
openvpn
opera-ffmpeg-codecs
optimus-manager
opus
orc
os-prober
p11-kit
p7zip
pacman
pacman-mirrorlist
pam
pambase
pango
pangomm
partclone
parted
partimage
pass
patch
pbzip2
pciutils
pcre
pcre2
pcsclite
pepper-flash
perl
perl-error
perl-mailtools
perl-timedate
perl-uri
perl-xml-parser
picom
pigz
pinentry
pixman
pixz
pkcs11-helper
pkgconf
po4a
polkit
polkit-qt5
poppler
poppler-glib
popt
ppp
pptpclient
print-manager
procps-ng
progsreiserfs
psmisc
pulseaudio
pulseaudio-alsa
pulsemixer
pygobject-devel
python
python-anytree
python-appdirs
python-cachecontrol
python-cairo
python-chardet
python-colorama
python-dbus
python-dbus-common
python-distlib
python-distro
python-gobject
python-html5lib
python-idna
python-importlib-metadata
python-lockfile
python-lxml
python-more-itertools
python-msgpack
python-ordered-set
python-packaging
python-pep517
python-pip
python-progress
python-pycups
python-pycurl
python-pygments
python-pyparsing
python-pytoml
python-requests
python-retrying
python-setuptools
python-six
python-urllib3
python-webencodings
python-zipp
python2
python2-dbus
python2-gobject2
python2-urwid
qjackctl
qpdf
qt5-base
qt5-declarative
qt5-imageformats
qt5-location
qt5-multimedia
qt5-quickcontrols
qt5-sensors
qt5-speech
qt5-svg
qt5-webchannel
qt5-webengine
qt5-webkit
qt5-websockets
qt5-x11extras
raptor
rasqal
re2
readline
redland
refind-efi
reiserfsprogs
rest
rhash
ristretto
rofi
rp-pppoe
rpcbind
rsync
rtkit
rubberband
ruby
rubygems
run-parts
screen
scrot
sdl
sdl2
sdparm
sed
semver
serd
serf
sg3_utils
shadow
shared-mime-info
slang
smartmontools
snappy
solid
sonnet
sord
sound-theme-freedesktop
speex
speexdsp
spice
sqlite
sratom
sshfs
startup-notification
steam
stoken
subversion
sudo
suil
swig
sysfsutils
syslinux
system-config-printer
systemd
systemd-libs
systemd-sysvcompat
t1lib
taglib
tar
tcl
tcpdump
tdb
teamspeak3
teamviewer
telegram-desktop
testdisk
texinfo
thin-provisioning-tools
thunar
thunderbird
tmate
tre
tree
tslib
ttf-hack
tumbler
tzdata
udisks2
unibilium
unrar
unzip
upower
usb_modeswitch
usbmuxd
usbutils
util-linux
v4l-utils
vamp-plugin-sdk
vi
vid.stab
vim
vim-runtime
virtualbox
virtualbox-host-dkms
vlc
volume_key
vpnc
vte-common
vte3
vulkan-icd-loader
wayland
wayland-protocols
webkit2gtk
webrtc-audio-processing
wget
which
wicd
wine-staging
wireless-regdb
wireless_tools
woff2
wpa_supplicant
wpebackend-fdo
wvdial
wvstreams
x264
x265
xarchiver
xcb-proto
xcb-util
xcb-util-cursor
xcb-util-image
xcb-util-keysyms
xcb-util-renderutil
xcb-util-wm
xcb-util-xrm
xclip
xdg-dbus-proxy
xdg-user-dirs
xdg-utils
xf86-input-evdev
xf86-input-keyboard
xf86-input-libinput
xf86-input-mouse
xf86-input-synaptics
xf86-input-vmmouse
xf86-input-void
xf86-video-amdgpu
xf86-video-ati
xf86-video-dummy
xf86-video-fbdev
xf86-video-intel
xf86-video-nouveau
xf86-video-openchrome
xf86-video-qxl
xf86-video-vesa
xf86-video-vmware
xf86-video-voodoo
xfce4-taskmanager
xfce4-terminal
xfconf
xfsprogs
xkeyboard-config
xl2tpd
xmlsec
xmlto
xorg-bdftopcf
xorg-docs
xorg-font-util
xorg-font-utils
xorg-fonts-100dpi
xorg-fonts-75dpi
xorg-fonts-alias
xorg-fonts-encodings
xorg-iceauth
xorg-luit
xorg-mkfontscale
xorg-server
xorg-server-common
xorg-server-devel
xorg-server-xdmx
xorg-server-xephyr
xorg-server-xnest
xorg-server-xvfb
xorg-server-xwayland
xorg-sessreg
xorg-setxkbmap
xorg-smproxy
xorg-util-macros
xorg-x11perf
xorg-xauth
xorg-xbacklight
xorg-xcmsdb
xorg-xcursorgen
xorg-xdpyinfo
xorg-xdriinfo
xorg-xev
xorg-xgamma
xorg-xhost
xorg-xinit
xorg-xinput
xorg-xkbcomp
xorg-xkbevd
xorg-xkbutils
xorg-xkill
xorg-xlsatoms
xorg-xlsclients
xorg-xmodmap
xorg-xpr
xorg-xprop
xorg-xrandr
xorg-xrdb
xorg-xrefresh
xorg-xset
xorg-xsetroot
xorg-xvinfo
xorg-xwd
xorg-xwininfo
xorg-xwud
xorgproto
xplc
xvidcore
xz
yajl
yelp-tools
yelp-xsl
zenity
zeromq
zip
zita-alsa-pcmi
zita-resampler
zlib
zsh
zstd
----
